name: Pre-Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.LICHTBLICK_GITHUB_TOKEN }}
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 16.17

      - name: Enable corepack
        run: corepack enable yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Read version from package.json
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build prod files
        run: |
          yarn run desktop:build:dev

      - name: Build Windows version
        run: yarn run package:win

      - name: Build Linux version
        run: yarn run package:linux

      - name: Build macOS version
        run: yarn run package:darwin

      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: lichtblick-build-${{ env.version }}
          path: |
            dist/lichtblick-${{ env.version }}-linux-amd64.deb
            dist/lichtblick-${{ env.version }}-linux-x64.tar.gz
            dist/lichtblick-${{ env.version }}-linux-arm64.deb
            dist/lichtblick-${{ env.version }}-linux-arm64.tar.gz
            dist/lichtblick-${{ env.version }}-mac-universal.dmg
            dist/lichtblick-${{ env.version }}-win.exe
            dist/latest-linux.yml
            dist/latest-mac.yml
            dist/latest.yml
          retention-days: 7
